version: '3'
networks: 
  app-network:
    driver: bridge
services:
  mysql_db:
    image: "mysql:5.7"
    container_name: mysql_db
    # ports:
    #   - '3306:3306'
    # restart: always
    # expose: 
    #   - 3306
    environment: 
      MYSQL_ROOT_PASSWORD: 'root'
    networks: 
        - app-network
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - /app/node_modules
      - ./server:/app
    networks:
      - app-network
    environment: 
      - MYSQL_HOST=mysql_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PORT=3306
    depends_on: 
      - mysql_db
    # links: 
      # - mysql_db
    # command: ./wait-for.sh mysql_db:3308 -- npm run dev

