version: '3'
networks: 
  app-network:
    driver: bridge
services:
  mysql_db:
    image: "mysql:5.7"
    container_name: mysql_db
    ports:
      - '3307:3306'
    expose: 
      - 3307
    environment: 
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'social'